import { z } from 'zod';

export const StreamSchema = z.object({
  url: z.string(),
  mimeType: z.string().optional(),
  bitrate: z.number().optional(),
  height: z.number().optional(),
  width: z.number().optional(),
  videoOnly: z.boolean().optional(),
});

export const CaptionSchema = z.object({
  label: z.string(),
  code: z.string(),
  url: z.string(),
  autoGenerated: z.boolean().default(false),
});

export const RelatedVideoSchema = z.object({
  videoId: z.string(),
  title: z.string().default(''),
  thumbnail: z.string().default(''),
  uploaderName: z.string().default(''),
  uploaderAvatar: z.string().default(''),
  uploaderUrl: z.string().default(''),
  views: z.number().default(0),
  duration: z.number().default(0),
  uploadedDate: z.string().default(''),
});

export const VideoInfoSchema = z.object({
  videoId: z.string(),
  title: z.string(),
  description: z.string().default(''),
  uploaderName: z.string().default(''),
  uploaderUrl: z.string().default(''),
  uploaderAvatar: z.string().default(''),
  uploaderSubscriberCount: z.number().default(0),
  views: z.number().default(0),
  uploadDate: z.string().default(''),
  duration: z.number().default(0),
  thumbnail: z.string().default(''),
  hls: z.string().nullable().default(null),
  livestream: z.boolean().default(false),
  audioStreams: z.array(StreamSchema).default([]),
  videoStreams: z.array(StreamSchema).default([]),
  videoOnlyStreams: z.array(StreamSchema).default([]),
  captions: z.array(CaptionSchema).default([]),
  relatedStreams: z.array(RelatedVideoSchema).default([]),
});
