import { Hono } from 'hono';
import {
  DEFAULT_PIPED_INSTANCES as PIPED_INSTANCES,
  VideoInfoSchema,
  FALLBACK_VIDEOS,
} from '@yourtebu/shared';
import { validateResponse } from '../middleware/validator.js';

const app = new Hono();
let currentInstanceIdx = 0;

function getPipedInstance() {
  return PIPED_INSTANCES[currentInstanceIdx];
}

function rotateInstance() {
  currentInstanceIdx = (currentInstanceIdx + 1) % PIPED_INSTANCES.length;
}

app.get('/:id', async (c) => {
  const id = c.req.param('id');

  for (let i = 0; i < PIPED_INSTANCES.length; i++) {
    const instance = getPipedInstance();
    try {
      const res = await fetch(`${instance}/streams/${id}`);
      if (res.ok) {
        const rawData = await res.json();
        const normalized = {
          videoId: id,
          title: rawData.title || '',
          description: rawData.description || '',
          uploaderName: rawData.uploader || rawData.uploaderName || '',
          uploaderUrl: rawData.uploaderUrl || '',
          uploaderAvatar: rawData.uploaderAvatar || '',
          uploaderSubscriberCount: rawData.uploaderSubscriberCount || 0,
          views: rawData.views || 0,
          uploadDate: rawData.uploadDate || rawData.uploaded || '',
          duration: rawData.duration || 0,
          thumbnail: rawData.thumbnailUrl || `https://i.ytimg.com/vi/${id}/hqdefault.jpg`,
          hls: rawData.hls || null,
          livestream: rawData.livestream || false,
          audioStreams: (rawData.audioStreams || []).map((s) => ({
            url: s.url,
            mimeType: s.mimeType,
            bitrate: s.bitrate,
          })),
          videoStreams: (rawData.videoStreams || [])
            .filter((s) => !s.videoOnly)
            .map((s) => ({
              url: s.url,
              mimeType: s.mimeType,
              height: s.height,
              width: s.width,
              videoOnly: false,
            })),
          videoOnlyStreams: (rawData.videoStreams || [])
            .filter((s) => s.videoOnly)
            .map((s) => ({
              url: s.url,
              mimeType: s.mimeType,
              height: s.height,
              width: s.width,
              videoOnly: true,
            })),
          captions: (rawData.subtitles || []).map((sub) => ({
            label: sub.name || sub.code,
            code: sub.code,
            url: sub.url,
            autoGenerated: sub.autoGenerated || false,
          })),
          relatedStreams: (rawData.relatedStreams || []).map((r) => ({
            videoId: r.url ? r.url.replace('/watch?v=', '') : '',
            title: r.title || '',
            thumbnail: r.thumbnail || '',
            uploaderName: r.uploaderName || '',
            uploaderAvatar: r.uploaderAvatar || '',
            uploaderUrl: r.uploaderUrl || '',
            views: r.views || 0,
            duration: r.duration || 0,
            uploadedDate: r.uploadedDate || r.uploaded || '',
          })),
        };

        const validated = validateResponse(VideoInfoSchema, normalized);
        return c.json(validated);
      }
    } catch {
      rotateInstance();
    }
  }

  // Fallback to local catalog video
  const found = FALLBACK_VIDEOS.find((v) => v.videoId === id) || FALLBACK_VIDEOS[0];
  return c.json(found);
});

export default app;
