export const FALLBACK_VIDEOS = [
  {
    videoId: '3JZ_D3ELwOQ',
    title: 'Sơn Tùng M-TP | CHÚNG TA CỦA TƯƠNG LAI | OFFICIAL MUSIC VIDEO',
    uploaderName: 'Sơn Tùng M-TP Official',
    views: 65000000,
    uploadDate: '2024-03-08',
    duration: 254,
    thumbnail: 'https://img.youtube.com/vi/3JZ_D3ELwOQ/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    livestream: false,
  },
  {
    videoId: 'jfKfPfyJRdk',
    title: 'lofi hip hop radio - beats to relax/study to ☕️ [LIVE 24/7]',
    uploaderName: 'Lofi Girl',
    views: 654000,
    uploadDate: 'Live now',
    duration: 0,
    thumbnail: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    category: 'live',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    livestream: true,
  },
  {
    videoId: 'fJ9rUzIMcZQ',
    title: 'Queen – Bohemian Rhapsody (Official Video Remastered)',
    uploaderName: 'Queen Official',
    views: 1600000000,
    uploadDate: '2008-08-01',
    duration: 359,
    thumbnail: 'https://img.youtube.com/vi/fJ9rUzIMcZQ/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    livestream: false,
  },
  {
    videoId: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    uploaderName: 'Luis Fonsi',
    views: 8200000000,
    uploadDate: '2017-01-12',
    duration: 282,
    thumbnail: 'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    livestream: false,
  },
  {
    videoId: 'L_LUpnjgPso',
    title: 'Ed Sheeran - Shape of You (Official Music Video)',
    uploaderName: 'Ed Sheeran',
    views: 6100000000,
    uploadDate: '2017-01-30',
    duration: 263,
    thumbnail: 'https://img.youtube.com/vi/L_LUpnjgPso/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    livestream: false,
  },
  {
    videoId: '9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE(강남스타일) M/V',
    uploaderName: 'Officialpsy',
    views: 5000000000,
    uploadDate: '2012-07-15',
    duration: 252,
    thumbnail: 'https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    livestream: false,
  },
  {
    videoId: '1w7OgIMMRc4',
    title: "Guns N' Roses - Sweet Child O' Mine (Official Music Video)",
    uploaderName: "Guns N' Roses",
    views: 1500000000,
    uploadDate: '2009-12-25',
    duration: 303,
    thumbnail: 'https://img.youtube.com/vi/1w7OgIMMRc4/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    livestream: false,
  },
  {
    videoId: 'hT_nvWreIhg',
    title: 'OneRepublic - Counting Stars (Official Music Video)',
    uploaderName: 'OneRepublic',
    views: 3800000000,
    uploadDate: '2013-05-31',
    duration: 284,
    thumbnail: 'https://img.youtube.com/vi/hT_nvWreIhg/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyplays.mp4',
    livestream: false,
  },
  {
    videoId: 'JGwWNGJdvx8',
    title: 'Ed Sheeran - Thinking Out Loud (Official Music Video)',
    uploaderName: 'Ed Sheeran',
    views: 3600000000,
    uploadDate: '2014-10-07',
    duration: 297,
    thumbnail: 'https://img.youtube.com/vi/JGwWNGJdvx8/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    livestream: false,
  },
  {
    videoId: '09R8_2nJtjg',
    title: 'Maroon 5 - Sugar (Official Music Video)',
    uploaderName: 'Maroon 5',
    views: 3900000000,
    uploadDate: '2015-01-14',
    duration: 301,
    thumbnail: 'https://img.youtube.com/vi/09R8_2nJtjg/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    livestream: false,
  },
  {
    videoId: 'YQHsXMglC9A',
    title: 'Adele - Hello (Official Music Video)',
    uploaderName: 'Adele',
    views: 3000000000,
    uploadDate: '2015-10-22',
    duration: 367,
    thumbnail: 'https://img.youtube.com/vi/YQHsXMglC9A/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutback2012.mp4',
    livestream: false,
  },
  {
    videoId: 'OPf0YbXqDm0',
    title: 'Mark Ronson - Uptown Funk ft. Bruno Mars',
    uploaderName: 'Mark Ronson',
    views: 4800000000,
    uploadDate: '2014-11-19',
    duration: 270,
    thumbnail: 'https://img.youtube.com/vi/OPf0YbXqDm0/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    livestream: false,
  },
  {
    videoId: 'rtOvBOTyX00',
    title: 'Christina Perri - A Thousand Years [Official Music Video]',
    uploaderName: 'Christina Perri',
    views: 2300000000,
    uploadDate: '2011-10-26',
    duration: 288,
    thumbnail: 'https://img.youtube.com/vi/rtOvBOTyX00/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    livestream: false,
  },
  {
    videoId: 'RgKAFK5djSk',
    title: 'Wiz Khalifa - See You Again ft. Charlie Puth [Official Video]',
    uploaderName: 'Wiz Khalifa',
    views: 5900000000,
    uploadDate: '2015-04-06',
    duration: 237,
    thumbnail: 'https://img.youtube.com/vi/RgKAFK5djSk/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    livestream: false,
  },
  {
    videoId: 'SlPhMPn053o',
    title: 'Taylor Swift - Shake It Off (Official Music Video)',
    uploaderName: 'Taylor Swift',
    views: 3300000000,
    uploadDate: '2014-08-18',
    duration: 242,
    thumbnail: 'https://img.youtube.com/vi/SlPhMPn053o/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    livestream: false,
  },
  {
    videoId: 'CevxZvSJLk8',
    title: 'Katy Perry - Roar (Official Music Video)',
    uploaderName: 'Katy Perry',
    views: 3800000000,
    uploadDate: '2013-09-05',
    duration: 270,
    thumbnail: 'https://img.youtube.com/vi/CevxZvSJLk8/hqdefault.jpg',
    category: 'music',
    hls: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    livestream: false,
  },
];

export function getFallbackSearch(query) {
  if (!query) return FALLBACK_VIDEOS;
  const q = query.toLowerCase();
  const filtered = FALLBACK_VIDEOS.filter(
    (v) =>
      v.title.toLowerCase().includes(q) ||
      v.uploaderName.toLowerCase().includes(q) ||
      (v.category && v.category.toLowerCase().includes(q)),
  );
  return filtered.length > 0 ? filtered : FALLBACK_VIDEOS;
}
